# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\"\x97\x01\n\x05State\x12\x11\n\terrorCode\x18\x01 \x01(\x05\x12\x13\n\x0b\x63urr_cart_x\x18\x02 \x01(\x02\x12\x13\n\x0b\x63urr_cart_v\x18\x03 \x01(\x02\x12\x13\n\x0b\x63urr_cart_a\x18\x04 \x01(\x02\x12\x13\n\x0b\x63urr_pole_x\x18\x05 \x01(\x02\x12\x13\n\x0b\x63urr_pole_v\x18\x06 \x01(\x02\x12\x12\n\ncurr_imu_a\x18\x07 \x01(\x02\"z\n\x06\x43onfig\x12\x12\n\nmax_cart_x\x18\x01 \x01(\x02\x12\x12\n\nmax_cart_v\x18\x02 \x01(\x02\x12\x12\n\nmax_cart_a\x18\x03 \x01(\x02\x12\x10\n\x08hw_max_x\x18\x04 \x01(\x02\x12\x10\n\x08hw_max_v\x18\x05 \x01(\x02\x12\x10\n\x08hw_max_a\x18\x06 \x01(\x02\"M\n\x06Target\x12\x15\n\rtarget_cart_x\x18\x01 \x01(\x02\x12\x15\n\rtarget_cart_v\x18\x02 \x01(\x02\x12\x15\n\rtarget_cart_a\x18\x03 \x01(\x02*3\n\x0bMessageType\x12\t\n\x05RESET\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\r\n\tKEEPALIVE\x10\x02*y\n\x05\x45rror\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x0e\n\nNEED_RESET\x10\x01\x12\x0e\n\nX_OVERFLOW\x10\x02\x12\x0e\n\nV_OVERFLOW\x10\x04\x12\x0e\n\nA_OVERFLOW\x10\x08\x12\x11\n\rMOTOR_STALLED\x10\x10\x12\x0f\n\x0b\x45NDSTOP_HIT\x10 b\x06proto3')

_MESSAGETYPE = DESCRIPTOR.enum_types_by_name['MessageType']
MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
_ERROR = DESCRIPTOR.enum_types_by_name['Error']
Error = enum_type_wrapper.EnumTypeWrapper(_ERROR)
RESET = 0
UPDATE = 1
KEEPALIVE = 2
NO_ERROR = 0
NEED_RESET = 1
X_OVERFLOW = 2
V_OVERFLOW = 4
A_OVERFLOW = 8
MOTOR_STALLED = 16
ENDSTOP_HIT = 32


_STATE = DESCRIPTOR.message_types_by_name['State']
_CONFIG = DESCRIPTOR.message_types_by_name['Config']
_TARGET = DESCRIPTOR.message_types_by_name['Target']
State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:State)
  })
_sym_db.RegisterMessage(State)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:Config)
  })
_sym_db.RegisterMessage(Config)

Target = _reflection.GeneratedProtocolMessageType('Target', (_message.Message,), {
  'DESCRIPTOR' : _TARGET,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:Target)
  })
_sym_db.RegisterMessage(Target)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGETYPE._serialized_start=375
  _MESSAGETYPE._serialized_end=426
  _ERROR._serialized_start=428
  _ERROR._serialized_end=549
  _STATE._serialized_start=19
  _STATE._serialized_end=170
  _CONFIG._serialized_start=172
  _CONFIG._serialized_end=294
  _TARGET._serialized_start=296
  _TARGET._serialized_end=373
# @@protoc_insertion_point(module_scope)
